// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChangecolorController from "./changecolor_controller"
application.register("changecolor", ChangecolorController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
